import type { DashboardPayload, OnboardingContentResponse, UpdateHabitsInput } from '@purposemint/contracts';
import { useQuery, useQueryClient } from '@tanstack/react-query'; import { router } from 'expo-router'; import { useEffect, useState } from 'react'; import { Text } from 'react-native';
import { AppButton } from '@/components/AppButton'; import { AppScreen } from '@/components/AppScreen'; import { FormNotice } from '@/components/FormNotice'; import { HabitTemplatePicker } from '@/components/onboarding/HabitTemplatePicker'; import { QueryErrorState } from '@/components/QueryErrorState'; import { theme } from '@/constants/theme'; import { dashboardQueryKey, useDashboard } from '@/hooks/use-dashboard'; import { apiRequest } from '@/lib/api/client';
export default function ManageHabits(){
 const dashboard=useDashboard(),client=useQueryClient(); const content=useQuery({queryKey:['onboarding','content'],queryFn:()=>apiRequest<OnboardingContentResponse>('/onboarding/content',{authenticated:true})}); const [selected,setSelected]=useState<string[]>([]),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);
 useEffect(()=>{if(dashboard.data)setSelected(dashboard.data.habits.filter(x=>x.isActive).map(x=>x.templateId))},[dashboard.data]);
 if(dashboard.isError)return <QueryErrorState message={dashboard.error instanceof Error?dashboard.error.message:'Please try again.'} onRetry={()=>void dashboard.refetch()}/>;
 if(content.isError)return <QueryErrorState message={content.error instanceof Error?content.error.message:'Please try again.'} onRetry={()=>void content.refetch()}/>;
 if(!content.data||!dashboard.data)return <AppScreen><Text>Loading your habits…</Text></AppScreen>;
 return <AppScreen contentContainerStyle={{gap:16}}><Text style={{color:theme.colors.text,fontSize:28,fontWeight:'900'}}>Update Habits</Text><Text style={{color:theme.colors.mutedText}}>Choose the habits you want active on your dashboard.</Text><HabitTemplatePicker templates={content.data.habitTemplates} selected={selected} onChange={setSelected}/><FormNotice message={error??undefined}/><AppButton accessibilityLabel="Save Habits" loading={saving} onPress={()=>void(async()=>{setSaving(true);setError(null);try{const data=await apiRequest<DashboardPayload,UpdateHabitsInput>('/habits',{authenticated:true,method:'PATCH',body:{templateIds:selected}});client.setQueryData(dashboardQueryKey,data);router.back()}catch(e){setError(e instanceof Error?e.message:'Please try again.')}finally{setSaving(false)}})()} title="Save Habits"/></AppScreen>;
}
