import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { PathwayApplicationStatus, Tier, type CreatePathwayApplicationInput, type PartnerPublic, type PartnersListResponse, type PathwayApplicationPublic, type PathwayPublic, type PathwaysListResponse, type SelectPathwayPartnersInput, type UpdateChecklistItemInput, type VerifyPathwayApplicationInput } from '@purposemint/contracts';
import { In, Repository } from 'typeorm';
import { ChecklistTemplate } from '../entities/checklist-template.entity'; import { Partner } from '../entities/partner.entity'; import { PathwayApplicationPartner } from '../entities/pathway-application-partner.entity'; import { PathwayApplication } from '../entities/pathway-application.entity'; import { PathwayChecklistItem } from '../entities/pathway-checklist-item.entity'; import { Pathway } from '../entities/pathway.entity'; import { User } from '../entities/user.entity';

@Injectable()
export class PathwaysService {
 constructor(@InjectRepository(Pathway) private readonly pathways: Repository<Pathway>, @InjectRepository(Partner) private readonly partners: Repository<Partner>, @InjectRepository(PathwayApplication) private readonly applications: Repository<PathwayApplication>, @InjectRepository(PathwayChecklistItem) private readonly checklistItems: Repository<PathwayChecklistItem>) {}
 async list(userId:string):Promise<PathwaysListResponse>{ await this.requireElevation(userId); return {pathways:(await this.pathways.find({order:{sortOrder:'ASC'}})).map(this.toPathway)}; }
 async listPartners(userId:string,key:string):Promise<PartnersListResponse>{ await this.requireElevation(userId); await this.requirePathway(key); return {partners:(await this.partners.find({where:{pathwayKey:key,isActive:true},order:{sortOrder:'ASC'}})).map(this.toPartner)}; }
 async createOrResume(userId:string,input:CreatePathwayApplicationInput):Promise<PathwayApplicationPublic>{
  await this.requireElevation(userId); await this.requirePathway(input.pathwayKey);
  try { const id=await this.applications.manager.transaction(async m=>{ await m.findOneOrFail(User,{where:{id:userId},lock:{mode:'pessimistic_write'}}); const prior=await m.findOne(PathwayApplication,{where:{userId,pathwayKey:input.pathwayKey,status:PathwayApplicationStatus.DRAFT}}); if(prior)return prior.id; return (await m.save(m.create(PathwayApplication,{userId,pathwayKey:input.pathwayKey,status:PathwayApplicationStatus.DRAFT,attestedAmount:null,attestationAcceptedAt:null,submittedAt:null}))).id; }); return this.get(userId,id); }
  catch(error){ if(this.unique(error)){ const prior=await this.applications.findOne({where:{userId,pathwayKey:input.pathwayKey,status:PathwayApplicationStatus.DRAFT}}); if(prior)return this.get(userId,prior.id); } throw error; }
 }
 async verify(userId:string,id:string,input:VerifyPathwayApplicationInput){ await this.requireElevation(userId); await this.applications.manager.transaction(async m=>{ const app=await this.lockDraft(m,userId,id); const pathway=await m.findOneByOrFail(Pathway,{key:app.pathwayKey}); if(input.attestedAmount<pathway.minimumAmount)throw new BadRequestException(`You need at least $${pathway.minimumAmount.toFixed(2)} in savings for this pathway.`); if(!input.attestationAccepted)throw new BadRequestException('Confirm that your savings amount is accurate to continue.'); app.attestedAmount=input.attestedAmount; app.attestationAcceptedAt=new Date(); await m.save(app); }); return this.get(userId,id); }
 async selectPartners(userId:string,id:string,input:SelectPathwayPartnersInput){ await this.requireElevation(userId); await this.applications.manager.transaction(async m=>{ const app=await this.lockDraft(m,userId,id); const unique=[...new Set(input.partnerIds)]; const matches=await m.find(Partner,{where:{id:In(unique),pathwayKey:app.pathwayKey,isActive:true}}); if(matches.length!==unique.length)throw new BadRequestException("One or more selected partners aren't available for this pathway."); await m.delete(PathwayApplicationPartner,{applicationId:id}); await m.insert(PathwayApplicationPartner,unique.map(partnerId=>({applicationId:id,partnerId}))); }); return this.get(userId,id); }
 async submit(userId:string,id:string){ await this.requireElevation(userId); await this.applications.manager.transaction(async m=>{ const app=await this.lockDraft(m,userId,id); const pathway=await m.findOneByOrFail(Pathway,{key:app.pathwayKey}); if(!app.attestationAcceptedAt||app.attestedAmount===null||app.attestedAmount<pathway.minimumAmount)throw new BadRequestException('Verify the required savings amount before submitting.'); if(await m.count(PathwayApplicationPartner,{where:{applicationId:id}})<1)throw new BadRequestException('Select at least one partner before submitting.'); const templates=await m.find(ChecklistTemplate,{where:{pathwayKey:app.pathwayKey},order:{sortOrder:'ASC'}}); if(!templates.length)throw new BadRequestException("This pathway's readiness checklist isn't available yet."); await m.createQueryBuilder().insert().into(PathwayChecklistItem).values(templates.map(t=>({applicationId:id,checklistTemplateId:t.id,isComplete:false,completedAt:null}))).orIgnore().execute(); app.status=PathwayApplicationStatus.SUBMITTED; app.submittedAt=new Date(); await m.save(app); }); return this.get(userId,id); }
 async get(userId:string,id:string):Promise<PathwayApplicationPublic>{ await this.requireElevation(userId); const app=await this.applications.findOne({where:{id,userId},relations:{pathway:true,applicationPartners:{partner:true},checklistItems:{checklistTemplate:true}}}); if(!app||!app.pathway)throw new NotFoundException("We couldn't find that pathway application."); return {id:app.id,pathway:this.toPathway(app.pathway),attestedAmount:app.attestedAmount,attestationAcceptedAt:app.attestationAcceptedAt?.toISOString()??null,verificationMethod:app.verificationMethod,status:app.status,submittedAt:app.submittedAt?.toISOString()??null,partners:(app.applicationPartners??[]).flatMap(r=>r.partner?[this.toPartner(r.partner)]:[]).sort((a,b)=>a.sortOrder-b.sortOrder),checklistItems:(app.checklistItems??[]).flatMap(i=>i.checklistTemplate?[{id:i.id,category:i.checklistTemplate.category,title:i.checklistTemplate.title,description:i.checklistTemplate.description,isComplete:i.isComplete,completedAt:i.completedAt?.toISOString()??null,sortOrder:i.checklistTemplate.sortOrder}]:[]).sort((a,b)=>a.sortOrder-b.sortOrder),createdAt:app.createdAt.toISOString(),updatedAt:app.updatedAt.toISOString()}; }
 async updateChecklist(userId:string,id:string,input:UpdateChecklistItemInput){ await this.requireElevation(userId); await this.checklistItems.manager.transaction(async m=>{ const item=await m.createQueryBuilder(PathwayChecklistItem,'item').innerJoinAndSelect('item.application','application').where('item.id = :id',{id}).andWhere('application.user_id = :userId',{userId}).andWhere('application.status = :status',{status:PathwayApplicationStatus.SUBMITTED}).setLock('pessimistic_write').getOne(); if(!item)throw new NotFoundException("We couldn't find that checklist item."); item.isComplete=input.isComplete; item.completedAt=input.isComplete?new Date():null; await m.save(item); }); const saved=await this.checklistItems.findOne({where:{id},relations:{checklistTemplate:true}}); if(!saved?.checklistTemplate)throw new NotFoundException("We couldn't find that checklist item."); return {id:saved.id,category:saved.checklistTemplate.category,title:saved.checklistTemplate.title,description:saved.checklistTemplate.description,isComplete:saved.isComplete,completedAt:saved.completedAt?.toISOString()??null,sortOrder:saved.checklistTemplate.sortOrder}; }
 private async requireElevation(userId:string){ const user=await this.applications.manager.findOne(User,{where:{id:userId},select:{id:true,tier:true}}); if(!user)throw new NotFoundException('User not found.'); if(user.tier!==Tier.ELEVATE)throw new ForbiddenException('Pathways requires an Elevation membership.'); }
 private async requirePathway(key:string){ const row=await this.pathways.findOneBy({key}); if(!row)throw new NotFoundException("We couldn't find that pathway."); return row; }
 private async lockDraft(m:Repository<PathwayApplication>['manager'],userId:string,id:string){ const app=await m.findOne(PathwayApplication,{where:{id,userId,status:PathwayApplicationStatus.DRAFT},lock:{mode:'pessimistic_write'}}); if(!app)throw new NotFoundException("We couldn't find an editable pathway application."); return app; }
 private unique(error:unknown){return typeof error==='object'&&error!==null&&'driverError'in error&&typeof error.driverError==='object'&&error.driverError!==null&&'code'in error.driverError&&error.driverError.code==='23505';}
 private toPathway=(p:Pathway):PathwayPublic=>({key:p.key,title:p.title,description:p.description,minimumAmount:p.minimumAmount,iconEmoji:p.iconEmoji,whyThisAmountBody:p.whyThisAmountBody,whyThisAmountBreakdown:p.whyThisAmountBreakdown,sourceLabel:p.sourceLabel,sourceUrl:p.sourceUrl,sortOrder:p.sortOrder});
 private toPartner=(p:Partner):PartnerPublic=>({id:p.id,name:p.name,partnerType:p.partnerType,description:p.description,locationLabel:p.locationLabel,capabilityTags:p.capabilityTags,pathwayKey:p.pathwayKey,sortOrder:p.sortOrder});
}
