import type { PropsWithChildren, ReactNode } from 'react'; import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppScreen } from '@/components/AppScreen'; import { theme } from '@/constants/theme';
export function PathwayScreen({children}:PropsWithChildren){return <AppScreen contentContainerStyle={s.screen}>{children}</AppScreen>}
export function PathwayHeading({badge,title,sub}:{badge?:string;title:string;sub:string|ReactNode}){return <View style={s.center}>{badge?<Text style={s.badge}>{badge}</Text>:null}<Text style={s.heading}>{title}</Text><Text style={s.sub}>{sub}</Text></View>}
export function Card({children}:PropsWithChildren){return <View style={s.card}>{children}</View>}
export function Title({children}:PropsWithChildren){return <Text style={s.title}>{children}</Text>}
export function Body({children}:PropsWithChildren){return <Text style={s.body}>{children}</Text>}
export function Choice({label,selected,onPress,children}:{label:string;selected:boolean;onPress:()=>void;children:ReactNode}){return <Pressable accessibilityLabel={label} accessibilityRole="checkbox" accessibilityState={{checked:selected}} onPress={onPress} style={[s.card,selected&&s.selected]}>{children}</Pressable>}
const s=StyleSheet.create({screen:{gap:16},center:{alignItems:'center',gap:10},badge:{backgroundColor:theme.colors.lightMint,borderRadius:999,color:theme.colors.deepGreen,fontSize:12,fontWeight:'900',paddingHorizontal:12,paddingVertical:7},heading:{color:theme.colors.text,fontSize:28,fontWeight:'900',letterSpacing:-.6,textAlign:'center'},sub:{color:theme.colors.mutedText,fontSize:14,lineHeight:21,textAlign:'center'},card:{backgroundColor:theme.colors.white,borderColor:theme.colors.border,borderRadius:theme.radius.lg,borderWidth:1,gap:8,minHeight:44,padding:16},selected:{backgroundColor:theme.colors.lightMint,borderColor:theme.colors.deepGreen,borderWidth:2},title:{color:theme.colors.text,fontSize:16,fontWeight:'900'},body:{color:theme.colors.mutedText,fontSize:14,lineHeight:20},row:{alignItems:'center',flexDirection:'row',gap:10},between:{alignItems:'center',flexDirection:'row',justifyContent:'space-between'},chip:{alignSelf:'flex-start',backgroundColor:theme.colors.accentSoft,borderRadius:999,color:theme.colors.teal,fontSize:12,fontWeight:'800',paddingHorizontal:10,paddingVertical:6},error:{color:theme.colors.danger,fontSize:13},input:{backgroundColor:theme.colors.white,borderColor:theme.colors.border,borderRadius:16,borderWidth:1,color:theme.colors.text,fontSize:18,minHeight:52,paddingHorizontal:16},check:{alignItems:'center',borderColor:theme.colors.deepGreen,borderRadius:6,borderWidth:2,height:24,justifyContent:'center',width:24},checkOn:{backgroundColor:theme.colors.deepGreen},checkText:{color:theme.colors.white,fontWeight:'900'},divider:{backgroundColor:theme.colors.border,height:1},link:{color:theme.colors.deepGreen,fontSize:14,fontWeight:'800',minHeight:44,textAlignVertical:'center'},banner:{backgroundColor:theme.colors.paleGold,borderRadius:18,gap:4,padding:16},bannerTitle:{color:theme.colors.text,fontSize:18,fontWeight:'900'},muted:{color:theme.colors.mutedText,fontSize:12,lineHeight:18}});
export const pathwayStyles=s;
