import { ChecklistCategory } from '@purposemint/contracts';
import type { ChecklistTemplate } from '../entities/checklist-template.entity';
import type { Partner } from '../entities/partner.entity';
import type { Pathway } from '../entities/pathway.entity';

export const SEEDED_PATHWAYS: Omit<Pathway, 'partners' | 'checklistTemplates'>[] = [
 { key:'vehicle', title:'Vehicle Pathway', description:'Reliable transportation for work, family, and life', minimumAmount:2500, iconEmoji:'🚗', whyThisAmountBody:'A reliable vehicle starts with more than a down payment. $2,500 creates room for taxes, registration, insurance, and an initial repair reserve so transportation does not immediately destabilize your budget.', whyThisAmountBreakdown:[{label:'vehicle down payment',amount:1500},{label:'tax, title, and registration',amount:400},{label:'first insurance payment',amount:300},{label:'initial maintenance reserve',amount:300}], sourceLabel:'AAA Your Driving Costs', sourceUrl:'https://www.aaa.com/autorepair/drivingcosts', sortOrder:1 },
 { key:'housing', title:'Housing Pathway', description:'Safe, stable housing through homeownership or rental stability', minimumAmount:3000, iconEmoji:'🏠', whyThisAmountBody:"Moving costs roughly three months of rent before you ever unpack. $3,000 reflects what a typical family actually hands over at signing — deposit, first month, application and utility hookups — so you don't move in already behind.", whyThisAmountBreakdown:[{label:'security deposit',amount:1200},{label:"first month's rent",amount:1200},{label:'application, admin, and utility deposits',amount:300},{label:'moving costs and basic setup',amount:300}], sourceLabel:'HUD Fair Market Rents', sourceUrl:'https://www.huduser.gov/portal/datasets/fmr.html', sortOrder:2 },
 { key:'childcare', title:'Childcare Pathway', description:'Quality childcare access so you can work with peace of mind', minimumAmount:1200, iconEmoji:'🧸', whyThisAmountBody:'Starting quality childcare often means paying enrollment costs and the first weeks of care before your next paycheck arrives. $1,200 gives your family a practical opening cushion while work and care schedules settle.', whyThisAmountBreakdown:[{label:'enrollment and registration fees',amount:150},{label:'first two weeks of care',amount:700},{label:'backup care reserve',amount:250},{label:'supplies and transportation',amount:100}], sourceLabel:'Child Care Aware of America Examining the Gaps', sourceUrl:'https://info.childcareaware.org/examining-the-gaps-2026', sortOrder:3 },
 { key:'workforce', title:'Workforce Pathway', description:'Use your savings as practical collateral to access certifications, training, and high-paying careers—no degree required. We connect skills assessment with financial readiness so you can advance without taking on debt.', minimumAmount:750, iconEmoji:'🛠️', whyThisAmountBody:'Career training can create costs before it creates a paycheck. $750 helps cover enrollment, required materials, transportation, and a small testing reserve so you can complete the next credential without relying on high-cost debt.', whyThisAmountBreakdown:[{label:'course or enrollment deposit',amount:350},{label:'tools, books, or required gear',amount:175},{label:'exam and credential fees',amount:125},{label:'transportation reserve',amount:100}], sourceLabel:'CareerOneStop Training Resources', sourceUrl:'https://www.careeronestop.org/FindTraining/find-training.aspx', sortOrder:4 },
 { key:'business', title:'Business Pathway', description:'Start or grow your small business with proper funding', minimumAmount:2000, iconEmoji:'💼', whyThisAmountBody:'A small business needs enough cash to open responsibly and absorb early surprises. $2,000 creates a starter reserve for registration, equipment, inventory, and operating expenses before revenue becomes predictable.', whyThisAmountBreakdown:[{label:'registration, permits, and licenses',amount:250},{label:'equipment and tools',amount:750},{label:'opening inventory or materials',amount:600},{label:'early operating reserve',amount:400}], sourceLabel:'U.S. Small Business Administration Startup Costs', sourceUrl:'https://www.sba.gov/business-guide/plan-your-business/calculate-your-startup-costs', sortOrder:5 },
 { key:'living-benefits', title:'Living Benefits/Life Insurance', description:'Protect your family with living benefits and life insurance coverage', minimumAmount:600, iconEmoji:'🛡️', whyThisAmountBody:'Protection works best when the first premium does not compete with the rest of your budget. $600 provides a practical reserve for initial premiums, health records, and follow-up costs while you compare coverage carefully.', whyThisAmountBreakdown:[{label:'initial premium reserve',amount:400},{label:'medical records or exam costs',amount:75},{label:'beneficiary and document preparation',amount:50},{label:'follow-up payment cushion',amount:75}], sourceLabel:'NAIC Life Insurance Buyer’s Guide', sourceUrl:'https://content.naic.org/sites/default/files/publication-lig-lp-consumer-life.pdf', sortOrder:6 },
];

type PartnerSeed = Omit<Partner, 'id'|'pathway'>;
const PLACEHOLDER_PARTNERS: Array<[string,string,string,string,string,string[]]> = [
 ['vehicle','Community Auto Finance Network','Community Lender','Fair-rate vehicle financing and purchase coaching','Louisiana Statewide',['Preapproval','Vehicle budgeting','Credit coaching']],['vehicle','Reliable Ride Resource Center','Mobility Program','Vehicle inspections and repair planning before purchase','Multiple parishes',['Inspections','Repair planning','Buyer education']],
 ['childcare','Family Care Access Collaborative','Childcare Resource Network','Childcare referrals and subsidy navigation for working families','Louisiana Statewide',['Provider referrals','Subsidy navigation','Backup care']],['childcare','Bright Start Community Center','Family Support Program','Enrollment support and family-friendly care planning','Baton Rouge, LA',['Enrollment help','Care planning','Parent support']],
 ['workforce','Skills Forward Louisiana','Workforce Program','Short-term credential navigation and career coaching','Louisiana Statewide',['Skills assessment','Credential navigation','Career coaching']],['workforce','Trade Ready Training Fund','Community Training Partner','Training-cost planning and employer connections','Multiple parishes',['Training support','Employer connections','Exam preparation']],
 ['business','Main Street Microenterprise Center','Small Business Program','Startup coaching and responsible microloan preparation','Louisiana Statewide',['Business planning','Microloan readiness','Cash-flow coaching']],['business','Community Enterprise Credit Union','Credit Union','Small-business accounts and fair-rate startup financing','Baton Rouge, LA',['Business banking','Startup loans','Financial coaching']],
 ['living-benefits','Family Protection Resource Network','Insurance Education Program','Independent coverage education and beneficiary planning','Louisiana Statewide',['Coverage education','Beneficiary planning','Needs assessment']],['living-benefits','Community Benefits Navigator','Benefits Counseling Program','Plain-language support comparing protection options','Multiple parishes',['Plan comparison','Application support','Document review']],
];
export const SEEDED_PARTNERS: PartnerSeed[] = [
 {name:'HUD-Approved Housing Counseling',partnerType:'Housing Program',description:'Free homebuyer education and down payment assistance programs',locationLabel:'Louisiana Statewide',capabilityTags:['First-time homebuyers','Down payment assistance','Credit repair'],pathwayKey:'housing',isActive:true,sortOrder:1},
 {name:'Pelican State Credit Union',partnerType:'Credit Union',description:'Low-down payment mortgage options with competitive rates',locationLabel:'Baton Rouge, LA',capabilityTags:['FHA loans','3% down programs','Closing cost assistance'],pathwayKey:'housing',isActive:true,sortOrder:2},
 {name:'Habitat for Humanity Louisiana',partnerType:'Housing Program',description:'Affordable homeownership through sweat equity partnership',locationLabel:'Multiple parishes',capabilityTags:['Sweat equity','0% interest mortgages','Financial education'],pathwayKey:'housing',isActive:true,sortOrder:3},
 ...PLACEHOLDER_PARTNERS.map(([pathwayKey,name,partnerType,description,locationLabel,capabilityTags],index)=>({pathwayKey,name,partnerType,description,locationLabel,capabilityTags,isActive:true,sortOrder:index+1})),
];

type ChecklistSeed = Omit<ChecklistTemplate, 'id'|'pathway'>;
const custom: Record<string, Array<[string,string,string]>> = {
 vehicle:[['documentation','Driver license and insurance history','Gather a valid license and available insurance records'],['documentation','Vehicle needs worksheet','Document commute, passenger, and accessibility needs'],['financial_review','Transportation budget review','Review payment, fuel, insurance, and maintenance limits'],['financial_review','Credit report review','Reviewed with a qualified financial counselor'],['consultation','Vehicle purchase coaching','Complete a fair-purchase preparation session'],['consultation','Partner consultation scheduled','Meet with a selected transportation partner'],['next_steps','Independent inspection plan','Arrange an inspection before signing']],
 childcare:[['documentation','Child identity and enrollment records','Gather required identification and enrollment documents'],['documentation','Work and care schedule','Document the weekly schedule care must cover'],['financial_review','Childcare budget review','Review tuition, subsidy, and backup-care costs'],['financial_review','Assistance eligibility screening','Check eligibility for available childcare assistance'],['consultation','Provider selection consultation','Review quality, location, and schedule fit'],['consultation','Partner consultation scheduled','Meet with a selected childcare partner'],['next_steps','Provider visit scheduled','Arrange a visit before enrollment']],
 workforce:[['documentation','Employment and education history','Gather a current résumé and prior training records'],['documentation','Program requirements checklist','Document prerequisites, dates, and required equipment'],['financial_review','Training budget review','Review tuition, materials, testing, and transportation'],['financial_review','Funding eligibility screening','Check grants, employer benefits, and responsible aid'],['consultation','Skills assessment completed','Identify strengths and credential options'],['consultation','Partner consultation scheduled','Meet with a selected workforce partner'],['next_steps','Enrollment plan confirmed','Confirm the program, timeline, and next deadline']],
 business:[['documentation','Business concept summary','Write the customer, offer, and operating model'],['documentation','Registration requirements','Gather required licenses, permits, and filing details'],['financial_review','Startup budget review','Review startup costs and working-capital needs'],['financial_review','Cash-flow projection','Build a simple twelve-month cash-flow estimate'],['consultation','Business coaching session','Review readiness with a small-business advisor'],['consultation','Partner consultation scheduled','Meet with a selected business partner'],['next_steps','Funding readiness plan','Confirm responsible funding steps and milestones']],
 'living-benefits':[['documentation','Household protection inventory','List dependents, obligations, income, and current coverage'],['documentation','Beneficiary information','Gather accurate beneficiary names and contact details'],['financial_review','Coverage budget review','Review an affordable long-term premium range'],['financial_review','Existing benefits review','Compare employer and personal coverage already in place'],['consultation','Needs assessment completed','Estimate coverage needs with an education-first advisor'],['consultation','Partner consultation scheduled','Meet with a selected protection partner'],['next_steps','Policy comparison checklist','Compare exclusions, riders, costs, and insurer strength']],
};
const labels = {documentation:ChecklistCategory.DOCUMENTATION,financial_review:ChecklistCategory.FINANCIAL_REVIEW,consultation:ChecklistCategory.CONSULTATION,next_steps:ChecklistCategory.NEXT_STEPS} as const;
export const SEEDED_CHECKLIST_TEMPLATES: ChecklistSeed[] = [
 ['documentation','Proof of savings verification','Security deposit savings confirmed'],['documentation','Rental history documentation','Previous landlord references or lease history'],['financial_review','Proof of income','Pay stubs, tax return, or benefits letter'],['financial_review','Credit report review','Reviewed by housing counselor'],['consultation','Homebuyer education enrollment','HUD-approved course registration'],['consultation','Partner consultation scheduled','Initial meeting with housing counselor'],['next_steps','Down payment assistance screening','Eligibility check for assistance programs'],
].map(([category,title,description],sortOrder)=>({pathwayKey:'housing',category:labels[category as keyof typeof labels],title,description,sortOrder:sortOrder+1})).concat(Object.entries(custom).flatMap(([pathwayKey,items])=>items.map(([category,title,description],sortOrder)=>({pathwayKey,category:labels[category as keyof typeof labels],title,description,sortOrder:sortOrder+1}))));
