import type { ReflectionTheme } from '../entities/reflection-theme.entity';

export const SEEDED_REFLECTION_THEMES: Omit<ReflectionTheme, 'matches'>[] = [
  {
    key: 'money',
    label: 'Money',
    colorToken: 'pink',
    matchKeywords: [
      'money',
      'budget',
      'save',
      'saved',
      'saving',
      'savings',
      'debt',
      'bill',
      'bills',
      'rent',
      'paycheck',
      'borrow',
      'borrowed',
    ],
    encouragementLine:
      'Money is often on your mind. Give yourself room to notice what feels heavy and what feels possible.',
    sortOrder: 1,
  },
  {
    key: 'progress',
    label: 'Progress',
    colorToken: 'teal',
    matchKeywords: [
      'progress',
      'grew',
      'growth',
      'improving',
      'improved',
      'step',
      'steps',
      'steady',
      'better',
      'forward',
    ],
    encouragementLine:
      "You're noticing movement over time. Small shifts still count, even when the day feels uneven.",
    sortOrder: 2,
  },
  {
    key: 'family',
    label: 'Family',
    colorToken: 'gold',
    matchKeywords: [
      'family',
      'mom',
      'mother',
      'dad',
      'father',
      'parent',
      'parents',
      'child',
      'children',
      'brother',
      'sister',
      'spouse',
      'partner',
    ],
    encouragementLine:
      'Family keeps showing up in your reflections. You can hold care for them without losing sight of yourself.',
    sortOrder: 3,
  },
  {
    key: 'goals',
    label: 'Goals',
    colorToken: 'plum',
    matchKeywords: [
      'goal',
      'goals',
      'target',
      'plan',
      'planned',
      'planning',
      'milestone',
      'dream',
      'future',
    ],
    encouragementLine:
      "Your goals are part of the story you're telling. It is okay for the next step to change as life changes.",
    sortOrder: 4,
  },
];
